"""Core data model.

Two hard structural rules live here, because invariants that are only written
down in a README get violated eventually:

1.  Every point awarded carries `Evidence` with a source URL.  `DimensionScore`
    refuses to hold points without it, so an unevidenced score cannot be
    constructed at all.
2.  `Flag` has no points field.  Flags route to human review; they can never
    add score.  Some flags carry a `discount` that *reduces* a dimension's
    contribution (see scoring.flags), but nothing here can increase one.

The scoring pipeline is split into collection (network) and scoring (pure).
`ProfileSnapshot` is the seam: it is everything the scorer is allowed to see.
Because it is a plain serialisable record, any historical score can be
regenerated byte-for-byte from a stored snapshot plus a code version and a
weight set -- which is what the audit log requires.
"""

from __future__ import annotations

import hashlib
import json
from dataclasses import dataclass, field, asdict
from datetime import datetime, timezone
from typing import Any, Iterable

SCHEMA_VERSION = "1.0.0"


# --------------------------------------------------------------------------
# Evidence
# --------------------------------------------------------------------------


@dataclass(frozen=True)
class Evidence:
    """A single verifiable claim backing part of a score.

    `url` must be a public, human-openable link.  A candidate reading their own
    dossier has to be able to click every line of it.
    """

    claim: str
    url: str
    detail: str = ""

    def __post_init__(self) -> None:
        if not self.claim:
            raise ValueError("evidence requires a claim")
        if not self.url or not self.url.startswith(("http://", "https://")):
            raise ValueError(f"evidence requires a public URL, got {self.url!r}")

    def to_dict(self) -> dict[str, str]:
        return {"claim": self.claim, "url": self.url, "detail": self.detail}


# --------------------------------------------------------------------------
# Scores
# --------------------------------------------------------------------------


@dataclass
class DimensionScore:
    """Points earned on one rubric dimension, with the arithmetic exposed.

    `components` records the named sub-parts that produced `raw`, so a dossier
    can show "original repos 8.5 + commit volume 6.0 + completeness 4.0"
    rather than an unexplained 18.5.
    """

    key: str
    points: float
    max_points: float
    components: dict[str, float] = field(default_factory=dict)
    evidence: list[Evidence] = field(default_factory=list)
    notes: list[str] = field(default_factory=list)

    def __post_init__(self) -> None:
        if self.points < 0:
            raise ValueError(f"{self.key}: negative points ({self.points})")
        if self.points > self.max_points + 1e-9:
            raise ValueError(
                f"{self.key}: {self.points} exceeds dimension max {self.max_points}"
            )
        # Invariant 3: transparency. Points without a citation are not auditable,
        # so we refuse to build them.
        if self.points > 0 and not self.evidence:
            raise ValueError(
                f"{self.key}: {self.points} points awarded with no evidence -- "
                "every claim must link to its source"
            )
        self.points = round(float(self.points), 4)

    def to_dict(self) -> dict[str, Any]:
        return {
            "key": self.key,
            "points": round(self.points, 2),
            "max_points": self.max_points,
            "components": {k: round(v, 3) for k, v in self.components.items()},
            "evidence": [e.to_dict() for e in self.evidence],
            "notes": list(self.notes),
        }


@dataclass(frozen=True)
class Flag:
    """An authenticity or review signal.

    Deliberately has no points field.  `discount` is a multiplier in [0, 1]
    applied to a specific dimension component by the scorer; it can only ever
    shrink a score.  Invariant 4: flags never add score.
    """

    key: str
    severity: str  # "review" | "warn" | "critical"
    message: str
    evidence: tuple[Evidence, ...] = ()
    discount: float | None = None
    discounts_component: str | None = None

    def __post_init__(self) -> None:
        if self.severity not in ("review", "warn", "critical"):
            raise ValueError(f"unknown severity {self.severity!r}")
        if self.discount is not None and not (0.0 <= self.discount <= 1.0):
            raise ValueError(
                f"{self.key}: discount {self.discount} outside [0,1] -- "
                "flags may only reduce score"
            )

    def to_dict(self) -> dict[str, Any]:
        out: dict[str, Any] = {
            "key": self.key,
            "severity": self.severity,
            "message": self.message,
            "evidence": [e.to_dict() for e in self.evidence],
        }
        if self.discount is not None:
            out["discount"] = self.discount
            out["discounts_component"] = self.discounts_component
        return out


@dataclass
class CandidateScore:
    handle: str
    total: float
    dimensions: list[DimensionScore]
    flags: list[Flag]
    program: str
    window_start: str
    window_end: str
    snapshot_digest: str
    code_version: str
    scored_at: str
    weights_digest: str = ""

    @property
    def automated_total(self) -> float:
        return round(
            sum(d.points for d in self.dimensions if d.key in AUTOMATED_DIMENSIONS), 2
        )

    @property
    def application_total(self) -> float:
        return round(
            sum(d.points for d in self.dimensions if d.key in APPLICATION_DIMENSIONS), 2
        )

    def dimension(self, key: str) -> DimensionScore | None:
        for d in self.dimensions:
            if d.key == key:
                return d
        return None

    def to_dict(self) -> dict[str, Any]:
        return {
            "handle": self.handle,
            "total": round(self.total, 2),
            "automated_total": self.automated_total,
            "application_total": self.application_total,
            "program": self.program,
            "window": {"start": self.window_start, "end": self.window_end},
            "dimensions": [d.to_dict() for d in self.dimensions],
            "flags": [f.to_dict() for f in self.flags],
            "reproducibility": {
                "snapshot_digest": self.snapshot_digest,
                "weights_digest": self.weights_digest,
                "code_version": self.code_version,
                "schema_version": SCHEMA_VERSION,
                "scored_at": self.scored_at,
            },
        }


AUTOMATED_DIMENSIONS = (
    "shipping_agency",
    "consistency",
    "external_validation",
    "collaboration",
    "ecosystem_footprint",
    "frontier_signal",
)

APPLICATION_DIMENSIONS = (
    "context_statement",
    "trusted_referral",
)


# --------------------------------------------------------------------------
# Collected activity (the scorer's entire view of a person)
# --------------------------------------------------------------------------


@dataclass
class RepoActivity:
    name: str  # "owner/repo"
    owner: str
    is_fork: bool
    pushed_at: str | None
    created_at: str | None
    description: str = ""
    language: str | None = None
    topics: list[str] = field(default_factory=list)
    stars: int = 0
    has_releases: bool = False
    has_pages: bool = False
    has_description: bool = False
    homepage: str = ""
    license: str | None = None
    commits_in_window: int = 0
    commit_weeks: list[str] = field(default_factory=list)

    @property
    def url(self) -> str:
        return f"https://github.com/{self.name}"


@dataclass
class PullRequestActivity:
    repo: str  # "owner/repo"
    number: int
    title: str
    merged_at: str | None
    created_at: str | None
    is_own_repo: bool = False

    @property
    def url(self) -> str:
        return f"https://github.com/{self.repo}/pull/{self.number}"


@dataclass
class ReviewActivity:
    repo: str
    number: int
    submitted_at: str | None
    is_own_repo: bool = False

    @property
    def url(self) -> str:
        return f"https://github.com/{self.repo}/pull/{self.number}"


@dataclass
class Application:
    """Self-declared fields.

    Invariant 2: nothing about a person's background or circumstances may be
    inferred.  It enters here, from the person, or through a verified referrer,
    or not at all.  There is deliberately no field for anything derived from a
    name, location, photo, or avatar.
    """

    context_statement: str = ""
    context_factors: list[str] = field(default_factory=list)
    referrer_name: str = ""
    declared_repo: str = ""
    build_plan: str = ""  # collected, surfaced to reviewers, unscored by default
    # Did the applicant affirmatively accept the programme terms, and which
    # version. Displaying terms on a page is not agreement; an affirmative act
    # is, and it has to say what was agreed to or it means nothing later.
    accepted_terms: bool = False
    accepted_terms_version: str = ""
    extra: dict[str, Any] = field(default_factory=dict)


@dataclass
class ProfileSnapshot:
    """Everything the scorer sees. Serialisable, hashable, replayable."""

    handle: str
    account_created_at: str | None
    collected_at: str
    window_start: str
    window_end: str
    repos: list[RepoActivity] = field(default_factory=list)
    merged_prs: list[PullRequestActivity] = field(default_factory=list)
    reviews: list[ReviewActivity] = field(default_factory=list)
    active_weeks: list[str] = field(default_factory=list)
    application: Application = field(default_factory=Application)
    collection_notes: list[str] = field(default_factory=list)
    partial: bool = False

    @property
    def profile_url(self) -> str:
        return f"https://github.com/{self.handle}"

    @property
    def account_age_days(self) -> int | None:
        if not self.account_created_at:
            return None
        created = _parse_iso(self.account_created_at)
        end = _parse_iso(self.window_end)
        if created is None or end is None:
            return None
        return (end - created).days

    @property
    def original_repos(self) -> list[RepoActivity]:
        """Non-fork repos with a push inside the window.

        The "original" qualifier is doing real work: forked shells are the
        cheapest thing to manufacture, so they earn nothing on the agency
        dimension.
        """
        return [r for r in self.repos if not r.is_fork and r.commits_in_window > 0]

    def to_dict(self) -> dict[str, Any]:
        return asdict(self)

    def digest(self) -> str:
        """Stable content hash -- the anchor for reproducing a historical score."""
        payload = json.dumps(self.to_dict(), sort_keys=True, separators=(",", ":"))
        return "sha256:" + hashlib.sha256(payload.encode()).hexdigest()[:32]


# --------------------------------------------------------------------------
# helpers
# --------------------------------------------------------------------------


def _parse_iso(value: str | None) -> datetime | None:
    if not value:
        return None
    text = value.replace("Z", "+00:00")
    try:
        dt = datetime.fromisoformat(text)
    except ValueError:
        return None
    if dt.tzinfo is None:
        dt = dt.replace(tzinfo=timezone.utc)
    return dt


def iso_week(value: str | None) -> str | None:
    """ISO year-week key, e.g. '2026-W23'. The unit of the cadence signal."""
    dt = _parse_iso(value)
    if dt is None:
        return None
    year, week, _ = dt.isocalendar()
    return f"{year}-W{week:02d}"


def utc_now_iso() -> str:
    return datetime.now(timezone.utc).replace(microsecond=0).isoformat()


def dedupe_weeks(weeks: Iterable[str | None]) -> list[str]:
    """Distinct, sorted week keys.

    v1 double-counted weeks that appeared in more than one activity source
    (a push and a PR in the same week read as two).  Cadence is 'did this
    person show up that week', so the sources are unioned, not summed.
    """
    return sorted({w for w in weeks if w})
