#!/usr/bin/env python3
"""Render the per-program weights table that RUBRIC.md embeds.

RUBRIC.md is the transparency artifact: it tells an applicant what their score
is made of and invites them to reproduce it. That promise breaks silently the
moment a program's weights drift from the prose, and it broke exactly that way
once already -- the published rubric documented `celo-trial`'s weights while
the live programme scored on quite different ones, zeroing two whole documented
dimensions. Nothing failed, because nothing compared them.

So the table is generated from the configs rather than written by hand, and
`tests/test_rubric_matches_configs.py` fails the build when the committed table
and the configs disagree.

    tools/render_rubric_weights.py            # print the table
    tools/render_rubric_weights.py --check    # exit 1 if RUBRIC.md is stale
    tools/render_rubric_weights.py --write    # rewrite the block in RUBRIC.md
"""

from __future__ import annotations

import argparse
import pathlib
import sys

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent.parent))

from talent_engine.config import REFERENCE_WEIGHTS, load_program  # noqa: E402

ROOT = pathlib.Path(__file__).resolve().parent.parent
RUBRIC = ROOT / "RUBRIC.md"
BEGIN = "<!-- BEGIN GENERATED WEIGHTS -->"
END = "<!-- END GENERATED WEIGHTS -->"

DIMENSIONS = list(REFERENCE_WEIGHTS)


def programs() -> list[str]:
    return sorted(p.stem for p in (ROOT / "programs").glob("*.json"))


def render() -> str:
    keys = programs()
    cfgs = {k: load_program(k) for k in keys}
    head = "| dimension | " + " | ".join(f"`{k}`" for k in keys) + " |"
    rule = "|---|" + "---:|" * len(keys)
    rows = [head, rule]
    for dim in DIMENSIONS:
        cells = []
        for k in keys:
            w = cfgs[k].weights.get(dim, 0)
            cells.append("0" if not w else f"{w:g}")
        rows.append(f"| `{dim}` | " + " | ".join(cells) + " |")
    totals = " | ".join(f"**{sum(cfgs[k].weights.values()):g}**" for k in keys)
    rows.append("| **total** | " + totals + " |")
    return "\n".join(rows)


def block() -> str:
    return (
        BEGIN
        + "\n<!-- Generated by tools/render_rubric_weights.py. Do not edit by hand. -->\n\n"
        + render()
        + "\n\n"
        + END
    )


def current() -> str | None:
    text = RUBRIC.read_text()
    if BEGIN not in text or END not in text:
        return None
    return text[text.index(BEGIN) : text.index(END) + len(END)]


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    ap.add_argument("--write", action="store_true")
    args = ap.parse_args()

    want = block()
    if args.check:
        if current() != want:
            print("RUBRIC.md weights table is stale. Run --write.", file=sys.stderr)
            return 1
        print("RUBRIC.md weights table matches the program configs.")
        return 0
    if args.write:
        text = RUBRIC.read_text()
        cur = current()
        if cur is None:
            print("no BEGIN marker in RUBRIC.md", file=sys.stderr)
            return 1
        RUBRIC.write_text(text.replace(cur, want))
        print("RUBRIC.md updated.")
        return 0
    print(want)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
